### ISSUE TITLE
Missing methods and options when migrating

### ISSUE THREAD

**Issue by beaucollins** [statsig-io/js-client-monorepo#1]
- We use `Statsig.removeGateOverride` and `Statsig.overrideGate` via `import { Statsig } from 'statsig-react';` but I can't find any similar APIs via `@statsig/js-client`
 - We use `{ localMode: true }` for tests and storybook, is there something comparable in the new packages?

**Comment by daniel-statsig** [comment]
Hey @beaucollins, thanks for reporting.

- For local overrides, you can pull in `@statsig/js-local-overrides` or just build your own implementor of [OverrideAdapter](https://github.com/statsig-io/js-client-monorepo/blob/f64f9b119f89518210efdf5b9d9b919d4a40b0de/packages/client-core/src/OverrideAdapter.ts#L10). Which ever approach you go with, you will need to pass the override adapter to [StatsigOptions.overrideAdapter](https://github.com/statsig-io/js-client-monorepo/blob/main/packages/client-core/src/StatsigOptionsCommon.ts#L95).  I will update docs for this.
  - You might also find the [StatsigClientLocalOverrides.test](https://github.com/statsig-io/js-client-monorepo/blob/f64f9b119f89518210efdf5b9d9b919d4a40b0de/packages/combo/src/__tests__/StatsigClientLocalOverrides.test.ts) useful. 

- I will add localMode back as part of the next release
