### ISSUE TITLE
useStatsigClient returns a new object

### ISSUE THREAD

**Issue by bgmort** [statsig-io/js-client-monorepo#12]
`useStatsigClient` returns a new object each time it is called, which can lead to sneaky bugs and unexpected behavior, for example:

```ts
  // in a component
  const client = useStatsigClient()
  useEffect(() => {
    // this will be logged with each render since `client` keeps changing
    client.logEvent('page-load', pageId)
  }, [client, pageId])
```

It should probably just return the client, or if the proxy object is really necessary, should be wrapped with `useMemo()`

**Comment by daniel-statsig** [comment]
Hey @bgmort, I will add a useMemo around it. 

Note that it will still change when the user/values change, this is required so that any hooks that check gates/experiments will re-render to display new values.
