### ISSUE TITLE
No way to override stable ID from v 1.2

### ISSUE THREAD

**Issue by ranno-lauri** [statsig-io/js-client-monorepo#3]
StatsigClient options used to include `overrideStableID` property, that we use to provide our own UID from cookies. It was available in beta, but since updating to the newest version, it's no longer available. What is the alternative solution to this?

**Comment by daniel-statsig** [comment]
Hey @ranno-lauri, this was moved to be part of the StatsigUser.

This means it is now in the same location across Client (@statsig/js-client) and Server (statsig-node) SDKs.

See https://docs.statsig.com/client/javascript-sdk/migrating-from-statsig-js#overridestableid

Let me know if you need anything else
