### ISSUE TITLE
initializeAsync doesn't cause re-render of values when using StatsigProviderWithCacheWarming

### ISSUE THREAD

**Issue by intergalacticspacehighway** [statsig-io/js-client-monorepo#4]
## Issue

Repro - https://github.com/intergalacticspacehighway/statsig-init-async-repro

`StatsigProvider`'s re-renders are triggered by this [event](https://github.com/statsig-io/js-client-monorepo/blob/fb13de2717063a7eda99791aed1a5551b30324af/packages/react-bindings/src/StatsigProvider.tsx#L25). However, there is a case when this event doesn't trigger after values are fetched from network. It has to do with how `StatsigProviderWithCacheWarming` works. The bug is happening due to race condition caused by `StatsigProviderWithCacheWarming`. [StatsigProviderWithCacheWarming](https://github.com/statsig-io/js-client-monorepo/blob/fb13de2717063a7eda99791aed1a5551b30324af/packages/react-native-core/src/StatsigProviderWithCacheWarming.tsx#L30) calls `initializeSync` which calls [resetForUser](https://github.com/statsig-io/js-client-monorepo/blob/fb13de2717063a7eda99791aed1a5551b30324af/packages/js-client/src/StatsigClient.ts#L134) which basically copies and changes the reference of user property.

### The race condition cause
- We trigger `initializeAsync` in userland. Statsig triggers `initializeSync` inside cache warming.
- This causes [this condition ](https://github.com/statsig-io/js-client-monorepo/blob/fb13de2717063a7eda99791aed1a5551b30324af/packages/js-client/src/StatsigClient.ts#L170) to pass as user object changes in between of `initializeSync` and until network call finishes so it returns early. Thus the re-render mechanism doesn't trigger, causing it to not re-render with new values.

## Solution
- Make a deep equality check [here](https://github.com/statsig-io/js-client-monorepo/blob/fb13de2717063a7eda99791aed1a5551b30324af/packages/js-client/src/StatsigClient.ts#L170)?

## Unrelated
- There are sync caching solutions avalibale now for react native like [MMKV](https://github.com/mrousavy/react-native-mmkv) which can be utilized. Cache Warming APIs can also be improved to prevent `initializeSync` and `initializeAsync` at the same time.

**Comment by daniel-statsig** [comment]
Hey @intergalacticspacehighway, thanks for reporting. 

If you are calling initializeAsync before cache warming is complete, there isn't really any reason to even use cache warming. 

The docs could be clearer on when and when not to use cache warming.

I'm curious what you would expect to happen in this case? I think you may end up with an issue where the cached values might overwrite your newer Network values.

**Comment by intergalacticspacehighway** [comment]
@daniel-statsig Thanks. I ideally want a stale while revalidate like strategy. Serve it from the cache or fallback to default first and then get an update (re-render) from network values. We do not want to block the app render for `initializeAsync` to complete. You mean if we don't do cache warming then it will work as above? 

Also cache can be sync now with MMKV like solutions on native (but that is a separate issue)

**Comment by daniel-statsig** [comment]
Yes, if you just want the latest values and don't mind if they change results mid-session, you can just call `initializeAsync` directly after your client creation and just set cacheWarming to a promise that resolves immediately.

Something like:
```
const client = new StatsigClient(...);
client.initializeAsync();

const noopWarming = {
  result: Promise.resolve(),
  isResolved: true,
};

return <StatsigProviderRN client={client} cacheWarming={noopWarming}>
 <...>
</StatsigProviderRN>
```

This MMKV storage solution is new to me, but has come up in some other threads, I will investigate adding it as the default storage provider, or at the least an option via StatsigOptions. Thanks for flagging it.

**Comment by dhiyaulhaqZA** [comment]
Hi @daniel-statsig, in the latest @statsig/react-native-bindings (3.0.0) cacheWarming is missing, I there any similar way to use that? I got `ERROR  [Statsig] Attempting to alter AsyncStorage before it is ready. Values will not be persisted.`

**Comment by penomoto** [comment]
> Hi [@daniel-statsig](https://github.com/daniel-statsig), in the latest @statsig/react-native-bindings (3.0.0) cacheWarming is missing from `StatsigProviderRN`, I there any similar way to use that? I got `ERROR [Statsig] Attempting to alter AsyncStorage before it is ready. Values will not be persisted.`

We are also seeing this issue.  Was there a resolution to this issue?  

Thanks in advance!
