### ISSUE TITLE
Allow rendering while initializing values

### ISSUE THREAD

**Issue by twavv** [statsig-io/js-client-monorepo#5]
Howdy! Hopefully my understanding is correct, but please correct me if I'm missing anything.

We have an app that takes advantage of NextJS's `getStaticProps` for a lot of pages. We want to move to a world where we use `getServerSideProps` but that's not possible currently. In the meantime, we want to use Statsig but can't pre-populate the feature flag values during SSR.

It looks like `StatsigProvider` will not show children if the client is loading. This is unfortunate, because it forces us into one of two non-ideal options:
* Use `initializeSync` which doesn't load the data into the current instance until refresh (causing the user to not be opted in to the correct flags/experiments)
* Use `initializeAsync` which causes `StatsigProvider` to not render children until after it completes the load (causing a flash on the page while data is loading).

Is there a way to just shift the values after they're loaded? I understand this comes with the risk of layout shifts, but it's a tradeoff we're willing to make given current constraints with statically rendering the pages.

**Comment by daniel-statsig** [comment]
Hey @twavv, sorry for the late response. Are you able to share a simple NextJS app that reproduces your issue? 

Regardless, I think what you may be able to do is use `myClient.dataAdapter.prefetchData` to get the data an then synchronously switch to these values once they fetch has occurred, this way their is no 'loading' time.

Something like this:

```tsx
function useClientWithPrefetch(sdkKey: string, user: StatsigUser) {
  const client = useMemo(() => {
    const newClient = new StatsigClient(sdkKey, user, {
      logLevel: LogLevel.Debug,
    });
    newClient.initializeSync();

    newClient.dataAdapter
      .prefetchData(user)
      .then(() => {
        newClient.updateUserSync(user);
      })
      .catch((err) => {
        console.warn(err);
      });

    return newClient;
  }, [sdkKey, user]);

  return client;
}

export default function PrefetchExample({
  user,
}: {
  user: StatsigUser;
}): JSX.Element {
  const client = useClientWithPrefetch(DEMO_CLIENT_KEY, user);

  return (
    <StatsigProvider client={client}>
      <Content />
    </StatsigProvider>
  );
}

```

**Comment by twavv** [comment]
I haven't actually tested that but I don't think that will work because it breaks server-side (or, in our case) static rendering. We can't initialize the client until after hydration but we have to pass something to `StatsigProvider`. We still want to do the static rendering since only small parts of the subtree will change after loading the feature flag values.

**Comment by daniel-statsig** [comment]
Hmm, I don't quite follow your usecase, are you able to share some code?

Could you try just dynamically rendering the provider?

```
const nullableClient: StatsigClient | null = useMemo(() => {...}, []);

if (nullableClient == null) {
  return children;
}

return <StatsigProvider client={client} >
  {children}
</StatsigProvider>
```

I am hesitant to add something that just prevents the internal "Ready" checks and always renders, as the idea is that developers are forced to think about the current state of the Statsig values. This way you don't accidentally get into states where Flags flip mid-session and/or UI flickers.


`setData` (bootstrapping) and `prefetchData` were specifically added to allow "latest values" with `initializeSync`/`updateUserSync`.
