### ISSUE TITLE
first time user always fails

### ISSUE THREAD

**Issue by yogurtandjam** [statsig-io/js-client-monorepo#6]
regardless of what i set the userId to in the statsig react client, they will always fail the first gate check unless i use the `await initializeAsync` method - unfortunately that method gives the application some very interesting race conditions.

example snippet of the code.
Statisg config has the rule userId 'test-id' passes 100%

```
const statsigClient = new StatsigClient(
  import.meta.env.VITE_STATSIG_CLIENT_KEY ?? '',
  { userID: 'test-id' },
  {
    disableLogging: import.meta.env.VITE_DISABLE_STATSIG,
    disableStorage: import.meta.env.VITE_DISABLE_STATSIG,
  }
);
statsigClient.initializeSync();

export const someView = () => {
  const gateValue = use
};
```

If i clear localStorage before loading the app, it will always fail upon page load (and succeed upon subsequent loads).
For users who only use the application once, it makes statsig not very useful. Is there a recommended remedy?

**Comment by tore-statsig** [comment]
Thats correct - we cannot synchronously give you updated values. This is all documented:

https://docs.statsig.com/client/javascript-sdk/react#setup

https://docs.statsig.com/client/javascript-sdk#initialize-the-sdk

If you want to have the most up to date values and synchronously initialize, you must use bootstrapping.

https://docs.statsig.com/client/javascript-sdk/using-evaluations-data-adapter#bootstrapping
