### ISSUE TITLE
initializeAsync silently failing when initialize API domain is blocked

### ISSUE THREAD

**Issue by ericdudley** [statsig-io/js-client-monorepo#8]
I am using `@statsig/js-client` and trying to initialize with `initializeAsync`. I added a `.then` and `.catch` to this call, expecting errors to be thrown.

However, we realized that some of our users have a firewall that is blocking the new API urls for initialize/logging. This was silently failing, and an error is never thrown.

Is this expected? How would I be able to detect when the network call from `initializeAsync` has failed?

**Comment by daniel-statsig** [comment]
@ericdudley, sorry for the late reply here. Thanks for reporting. This blocking is a known problem and we are working on a solution internally. 

As for the error being silent, there should have been a log for the network error (https://github.com/statsig-io/js-client-monorepo/blob/main/packages/client-core/src/NetworkCore.ts#L170-L173). 

Is it possible that this did throw an error, but rather the network request just hangs?

We could look at piping this kind of thing through to the [ClientEmitter](https://docs.statsig.com/custom_proxy), but I'm curious what you would do if you detected these blocked requests? 

Today, the only guaranteed way to get around the blockers is to [proxy](https://docs.statsig.com/custom_proxy) all Statsig requests through your own domains.
